script: "bundle exec rake"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-head
  - jruby-18mode
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-18mode
before_install:
  - gem uninstall ffi -a
