language: ruby
script: bundle exec rake
bundler_args: --without perf
cache: bundler

rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.10
  - 2.5.8
  - 2.7.2
  - 3.0.0
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ree
    - rvm: ruby-head
    - rvm: jruby-head
